<?php

return [
    'base' => env('MIX_BASE_URL', '/'),
    'name' => env('MIX_APP_NAME', 'Laradmin'),
    'slug' => env('MIX_APP_SLUG', 'Laradmin'),
    'keywords' => 'Laravel, Bootstrap, Admin template',
    'description' => 'An admin boilerplate developed with Bootstrap and AdminLTE base on Laravel',
    'author' => 'Fu Rongxin',
    'powerby' => 'Fu Rongxin',
    'copyright' => 'Laradmin Company',
    'password' => '123456',

    // Status code,
    'code' => [
        100001 => 'Object is updating',

        200001 => 'Object created successfully',
        200002 => 'Object updated successfully',
        200003 => 'Object deleted successfully',
        200004 => 'Login Successful!',
        200005 => 'Logout Successful!',
        200006 => 'Password has been updated',
        200007 => 'Password reset successfully',
        200008 => 'File upload successfully',
        200009 => 'Data imported successfully',
        200010 => 'Data exported successfully',

        401001 => 'User is not authenticated',
        401002 => 'Account locked',
        401003 => 'User not enabled',
        402001 => 'System is down',
        403001 => 'Password reset failed',
        403002 => 'Failed to modify password',
        403003 => 'The old password is wrong, please re-enter',
        403004 => 'The confirmed password does not match the new password, please re-enter',
        405001 => 'Incorrect submission method',

        500001 => 'Object creation failed',
        500002 => 'Object update failed',
        500003 => 'Object deletion failed',
        500004 => 'Object does not exist',
        500005 => 'Role assignment failed',
        500006 => 'Permission assignment failed',
        500007 => 'The uploaded file is illegal',
        500008 => 'File upload failed',
        500009 => 'Data import failed',
        500010 => 'Data export failed',
    ],
];
